---

# Task 0: Enable IP forwarding
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes


# Task 1: Initialize Kubernetes Cluster
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf

# Task 2: Configure kubectl for the master node
- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf to kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

# Task 3: Install Pod network add-on (Calico)
- name: Download Calico manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/calico.yaml
    dest: /tmp/calico.yaml

- name: Apply Calico network manifest
  command: kubectl apply -f /tmp/calico.yaml

# Task 4: Generate Join Command for Worker Nodes
- name: Extract kubeadm join command
  shell: |
    kubeadm token create --print-join-command
  register: kubeadm_join_cmd

- name: Save kubeadm join command to a file
  copy:
    content: "{{ kubeadm_join_cmd.stdout }}"
    dest: /tmp/kubeadm_join_command.sh
    mode: '0755'